package com.sinodom.elevator.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sinodom.elevator.db.Inspect;
import com.sinodom.elevator.db.InspectItem;
import com.sinodom.elevator.db.Location;
import com.sinodom.elevator.db.Maintenance;
import com.sinodom.elevator.db.NfcBind;
import com.sinodom.elevator.db.PaperlessMaintenance;
import com.sinodom.elevator.db.Parts;
import com.sinodom.elevator.db.Session;
import com.sinodom.elevator.db.StatusAction;

import com.sinodom.elevator.db.greendao.InspectDao;
import com.sinodom.elevator.db.greendao.InspectItemDao;
import com.sinodom.elevator.db.greendao.LocationDao;
import com.sinodom.elevator.db.greendao.MaintenanceDao;
import com.sinodom.elevator.db.greendao.NfcBindDao;
import com.sinodom.elevator.db.greendao.PaperlessMaintenanceDao;
import com.sinodom.elevator.db.greendao.PartsDao;
import com.sinodom.elevator.db.greendao.SessionDao;
import com.sinodom.elevator.db.greendao.StatusActionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inspectDaoConfig;
    private final DaoConfig inspectItemDaoConfig;
    private final DaoConfig locationDaoConfig;
    private final DaoConfig maintenanceDaoConfig;
    private final DaoConfig nfcBindDaoConfig;
    private final DaoConfig paperlessMaintenanceDaoConfig;
    private final DaoConfig partsDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig statusActionDaoConfig;

    private final InspectDao inspectDao;
    private final InspectItemDao inspectItemDao;
    private final LocationDao locationDao;
    private final MaintenanceDao maintenanceDao;
    private final NfcBindDao nfcBindDao;
    private final PaperlessMaintenanceDao paperlessMaintenanceDao;
    private final PartsDao partsDao;
    private final SessionDao sessionDao;
    private final StatusActionDao statusActionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inspectDaoConfig = daoConfigMap.get(InspectDao.class).clone();
        inspectDaoConfig.initIdentityScope(type);

        inspectItemDaoConfig = daoConfigMap.get(InspectItemDao.class).clone();
        inspectItemDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        maintenanceDaoConfig = daoConfigMap.get(MaintenanceDao.class).clone();
        maintenanceDaoConfig.initIdentityScope(type);

        nfcBindDaoConfig = daoConfigMap.get(NfcBindDao.class).clone();
        nfcBindDaoConfig.initIdentityScope(type);

        paperlessMaintenanceDaoConfig = daoConfigMap.get(PaperlessMaintenanceDao.class).clone();
        paperlessMaintenanceDaoConfig.initIdentityScope(type);

        partsDaoConfig = daoConfigMap.get(PartsDao.class).clone();
        partsDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        statusActionDaoConfig = daoConfigMap.get(StatusActionDao.class).clone();
        statusActionDaoConfig.initIdentityScope(type);

        inspectDao = new InspectDao(inspectDaoConfig, this);
        inspectItemDao = new InspectItemDao(inspectItemDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);
        maintenanceDao = new MaintenanceDao(maintenanceDaoConfig, this);
        nfcBindDao = new NfcBindDao(nfcBindDaoConfig, this);
        paperlessMaintenanceDao = new PaperlessMaintenanceDao(paperlessMaintenanceDaoConfig, this);
        partsDao = new PartsDao(partsDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        statusActionDao = new StatusActionDao(statusActionDaoConfig, this);

        registerDao(Inspect.class, inspectDao);
        registerDao(InspectItem.class, inspectItemDao);
        registerDao(Location.class, locationDao);
        registerDao(Maintenance.class, maintenanceDao);
        registerDao(NfcBind.class, nfcBindDao);
        registerDao(PaperlessMaintenance.class, paperlessMaintenanceDao);
        registerDao(Parts.class, partsDao);
        registerDao(Session.class, sessionDao);
        registerDao(StatusAction.class, statusActionDao);
    }
    
    public void clear() {
        inspectDaoConfig.clearIdentityScope();
        inspectItemDaoConfig.clearIdentityScope();
        locationDaoConfig.clearIdentityScope();
        maintenanceDaoConfig.clearIdentityScope();
        nfcBindDaoConfig.clearIdentityScope();
        paperlessMaintenanceDaoConfig.clearIdentityScope();
        partsDaoConfig.clearIdentityScope();
        sessionDaoConfig.clearIdentityScope();
        statusActionDaoConfig.clearIdentityScope();
    }

    public InspectDao getInspectDao() {
        return inspectDao;
    }

    public InspectItemDao getInspectItemDao() {
        return inspectItemDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public MaintenanceDao getMaintenanceDao() {
        return maintenanceDao;
    }

    public NfcBindDao getNfcBindDao() {
        return nfcBindDao;
    }

    public PaperlessMaintenanceDao getPaperlessMaintenanceDao() {
        return paperlessMaintenanceDao;
    }

    public PartsDao getPartsDao() {
        return partsDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public StatusActionDao getStatusActionDao() {
        return statusActionDao;
    }

}
