package com.sinodom.elevator.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sinodom.elevator.db.Inspect;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INSPECT".
*/
public class InspectDao extends AbstractDao<Inspect, Long> {

    public static final String TABLENAME = "INSPECT";

    /**
     * Properties of entity Inspect.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property InspectId = new Property(1, int.class, "InspectId", false, "INSPECT_ID");
        public final static Property TypeID = new Property(2, int.class, "TypeID", false, "TYPE_ID");
        public final static Property TypeName = new Property(3, String.class, "TypeName", false, "TYPE_NAME");
        public final static Property StepId = new Property(4, int.class, "StepId", false, "STEP_ID");
        public final static Property StepName = new Property(5, String.class, "StepName", false, "STEP_NAME");
        public final static Property IsPassed = new Property(6, boolean.class, "IsPassed", false, "IS_PASSED");
        public final static Property Remark = new Property(7, String.class, "Remark", false, "REMARK");
        public final static Property PhotoUrl = new Property(8, String.class, "PhotoUrl", false, "PHOTO_URL");
        public final static Property VideoPath = new Property(9, String.class, "VideoPath", false, "VIDEO_PATH");
        public final static Property MapX = new Property(10, String.class, "MapX", false, "MAP_X");
        public final static Property MapY = new Property(11, String.class, "MapY", false, "MAP_Y");
        public final static Property IsPhoto = new Property(12, boolean.class, "IsPhoto", false, "IS_PHOTO");
        public final static Property Local = new Property(13, String.class, "Local", false, "LOCAL");
    }


    public InspectDao(DaoConfig config) {
        super(config);
    }
    
    public InspectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INSPECT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"INSPECT_ID\" INTEGER NOT NULL ," + // 1: InspectId
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 2: TypeID
                "\"TYPE_NAME\" TEXT," + // 3: TypeName
                "\"STEP_ID\" INTEGER NOT NULL ," + // 4: StepId
                "\"STEP_NAME\" TEXT," + // 5: StepName
                "\"IS_PASSED\" INTEGER NOT NULL ," + // 6: IsPassed
                "\"REMARK\" TEXT," + // 7: Remark
                "\"PHOTO_URL\" TEXT," + // 8: PhotoUrl
                "\"VIDEO_PATH\" TEXT," + // 9: VideoPath
                "\"MAP_X\" TEXT," + // 10: MapX
                "\"MAP_Y\" TEXT," + // 11: MapY
                "\"IS_PHOTO\" INTEGER NOT NULL ," + // 12: IsPhoto
                "\"LOCAL\" TEXT);"); // 13: Local
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INSPECT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Inspect entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getInspectId());
        stmt.bindLong(3, entity.getTypeID());
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(4, TypeName);
        }
        stmt.bindLong(5, entity.getStepId());
 
        String StepName = entity.getStepName();
        if (StepName != null) {
            stmt.bindString(6, StepName);
        }
        stmt.bindLong(7, entity.getIsPassed() ? 1L: 0L);
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(8, Remark);
        }
 
        String PhotoUrl = entity.getPhotoUrl();
        if (PhotoUrl != null) {
            stmt.bindString(9, PhotoUrl);
        }
 
        String VideoPath = entity.getVideoPath();
        if (VideoPath != null) {
            stmt.bindString(10, VideoPath);
        }
 
        String MapX = entity.getMapX();
        if (MapX != null) {
            stmt.bindString(11, MapX);
        }
 
        String MapY = entity.getMapY();
        if (MapY != null) {
            stmt.bindString(12, MapY);
        }
        stmt.bindLong(13, entity.getIsPhoto() ? 1L: 0L);
 
        String Local = entity.getLocal();
        if (Local != null) {
            stmt.bindString(14, Local);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Inspect entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getInspectId());
        stmt.bindLong(3, entity.getTypeID());
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(4, TypeName);
        }
        stmt.bindLong(5, entity.getStepId());
 
        String StepName = entity.getStepName();
        if (StepName != null) {
            stmt.bindString(6, StepName);
        }
        stmt.bindLong(7, entity.getIsPassed() ? 1L: 0L);
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(8, Remark);
        }
 
        String PhotoUrl = entity.getPhotoUrl();
        if (PhotoUrl != null) {
            stmt.bindString(9, PhotoUrl);
        }
 
        String VideoPath = entity.getVideoPath();
        if (VideoPath != null) {
            stmt.bindString(10, VideoPath);
        }
 
        String MapX = entity.getMapX();
        if (MapX != null) {
            stmt.bindString(11, MapX);
        }
 
        String MapY = entity.getMapY();
        if (MapY != null) {
            stmt.bindString(12, MapY);
        }
        stmt.bindLong(13, entity.getIsPhoto() ? 1L: 0L);
 
        String Local = entity.getLocal();
        if (Local != null) {
            stmt.bindString(14, Local);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Inspect readEntity(Cursor cursor, int offset) {
        Inspect entity = new Inspect( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // InspectId
            cursor.getInt(offset + 2), // TypeID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // TypeName
            cursor.getInt(offset + 4), // StepId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // StepName
            cursor.getShort(offset + 6) != 0, // IsPassed
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Remark
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // PhotoUrl
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // VideoPath
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // MapX
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // MapY
            cursor.getShort(offset + 12) != 0, // IsPhoto
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // Local
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Inspect entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setInspectId(cursor.getInt(offset + 1));
        entity.setTypeID(cursor.getInt(offset + 2));
        entity.setTypeName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStepId(cursor.getInt(offset + 4));
        entity.setStepName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsPassed(cursor.getShort(offset + 6) != 0);
        entity.setRemark(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPhotoUrl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setVideoPath(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMapX(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMapY(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setIsPhoto(cursor.getShort(offset + 12) != 0);
        entity.setLocal(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Inspect entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Inspect entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Inspect entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
