package com.sinodom.elevator.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sinodom.elevator.db.InspectItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INSPECT_ITEM".
*/
public class InspectItemDao extends AbstractDao<InspectItem, Long> {

    public static final String TABLENAME = "INSPECT_ITEM";

    /**
     * Properties of entity InspectItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property InspectId = new Property(1, int.class, "InspectId", false, "INSPECT_ID");
        public final static Property StepId = new Property(2, int.class, "StepId", false, "STEP_ID");
        public final static Property StepName = new Property(3, String.class, "StepName", false, "STEP_NAME");
        public final static Property IsPassed = new Property(4, boolean.class, "IsPassed", false, "IS_PASSED");
        public final static Property PhotoUrl = new Property(5, String.class, "PhotoUrl", false, "PHOTO_URL");
        public final static Property Remark = new Property(6, String.class, "Remark", false, "REMARK");
        public final static Property TypeID = new Property(7, int.class, "TypeID", false, "TYPE_ID");
        public final static Property TypeName = new Property(8, String.class, "TypeName", false, "TYPE_NAME");
        public final static Property VideoPath = new Property(9, String.class, "VideoPath", false, "VIDEO_PATH");
        public final static Property MapX = new Property(10, String.class, "MapX", false, "MAP_X");
        public final static Property MapY = new Property(11, String.class, "MapY", false, "MAP_Y");
        public final static Property IsPhoto = new Property(12, boolean.class, "IsPhoto", false, "IS_PHOTO");
        public final static Property UserId = new Property(13, int.class, "UserId", false, "USER_ID");
        public final static Property Local = new Property(14, String.class, "Local", false, "LOCAL");
        public final static Property UserName = new Property(15, String.class, "UserName", false, "USER_NAME");
        public final static Property CreateTime = new Property(16, String.class, "CreateTime", false, "CREATE_TIME");
        public final static Property TemplateAttributeJson = new Property(17, String.class, "TemplateAttributeJson", false, "TEMPLATE_ATTRIBUTE_JSON");
    }


    public InspectItemDao(DaoConfig config) {
        super(config);
    }
    
    public InspectItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INSPECT_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"INSPECT_ID\" INTEGER NOT NULL ," + // 1: InspectId
                "\"STEP_ID\" INTEGER NOT NULL ," + // 2: StepId
                "\"STEP_NAME\" TEXT," + // 3: StepName
                "\"IS_PASSED\" INTEGER NOT NULL ," + // 4: IsPassed
                "\"PHOTO_URL\" TEXT," + // 5: PhotoUrl
                "\"REMARK\" TEXT," + // 6: Remark
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 7: TypeID
                "\"TYPE_NAME\" TEXT," + // 8: TypeName
                "\"VIDEO_PATH\" TEXT," + // 9: VideoPath
                "\"MAP_X\" TEXT," + // 10: MapX
                "\"MAP_Y\" TEXT," + // 11: MapY
                "\"IS_PHOTO\" INTEGER NOT NULL ," + // 12: IsPhoto
                "\"USER_ID\" INTEGER NOT NULL ," + // 13: UserId
                "\"LOCAL\" TEXT," + // 14: Local
                "\"USER_NAME\" TEXT," + // 15: UserName
                "\"CREATE_TIME\" TEXT," + // 16: CreateTime
                "\"TEMPLATE_ATTRIBUTE_JSON\" TEXT);"); // 17: TemplateAttributeJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INSPECT_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, InspectItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getInspectId());
        stmt.bindLong(3, entity.getStepId());
 
        String StepName = entity.getStepName();
        if (StepName != null) {
            stmt.bindString(4, StepName);
        }
        stmt.bindLong(5, entity.getIsPassed() ? 1L: 0L);
 
        String PhotoUrl = entity.getPhotoUrl();
        if (PhotoUrl != null) {
            stmt.bindString(6, PhotoUrl);
        }
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(7, Remark);
        }
        stmt.bindLong(8, entity.getTypeID());
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(9, TypeName);
        }
 
        String VideoPath = entity.getVideoPath();
        if (VideoPath != null) {
            stmt.bindString(10, VideoPath);
        }
 
        String MapX = entity.getMapX();
        if (MapX != null) {
            stmt.bindString(11, MapX);
        }
 
        String MapY = entity.getMapY();
        if (MapY != null) {
            stmt.bindString(12, MapY);
        }
        stmt.bindLong(13, entity.getIsPhoto() ? 1L: 0L);
        stmt.bindLong(14, entity.getUserId());
 
        String Local = entity.getLocal();
        if (Local != null) {
            stmt.bindString(15, Local);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(16, UserName);
        }
 
        String CreateTime = entity.getCreateTime();
        if (CreateTime != null) {
            stmt.bindString(17, CreateTime);
        }
 
        String TemplateAttributeJson = entity.getTemplateAttributeJson();
        if (TemplateAttributeJson != null) {
            stmt.bindString(18, TemplateAttributeJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, InspectItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getInspectId());
        stmt.bindLong(3, entity.getStepId());
 
        String StepName = entity.getStepName();
        if (StepName != null) {
            stmt.bindString(4, StepName);
        }
        stmt.bindLong(5, entity.getIsPassed() ? 1L: 0L);
 
        String PhotoUrl = entity.getPhotoUrl();
        if (PhotoUrl != null) {
            stmt.bindString(6, PhotoUrl);
        }
 
        String Remark = entity.getRemark();
        if (Remark != null) {
            stmt.bindString(7, Remark);
        }
        stmt.bindLong(8, entity.getTypeID());
 
        String TypeName = entity.getTypeName();
        if (TypeName != null) {
            stmt.bindString(9, TypeName);
        }
 
        String VideoPath = entity.getVideoPath();
        if (VideoPath != null) {
            stmt.bindString(10, VideoPath);
        }
 
        String MapX = entity.getMapX();
        if (MapX != null) {
            stmt.bindString(11, MapX);
        }
 
        String MapY = entity.getMapY();
        if (MapY != null) {
            stmt.bindString(12, MapY);
        }
        stmt.bindLong(13, entity.getIsPhoto() ? 1L: 0L);
        stmt.bindLong(14, entity.getUserId());
 
        String Local = entity.getLocal();
        if (Local != null) {
            stmt.bindString(15, Local);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(16, UserName);
        }
 
        String CreateTime = entity.getCreateTime();
        if (CreateTime != null) {
            stmt.bindString(17, CreateTime);
        }
 
        String TemplateAttributeJson = entity.getTemplateAttributeJson();
        if (TemplateAttributeJson != null) {
            stmt.bindString(18, TemplateAttributeJson);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public InspectItem readEntity(Cursor cursor, int offset) {
        InspectItem entity = new InspectItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // InspectId
            cursor.getInt(offset + 2), // StepId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // StepName
            cursor.getShort(offset + 4) != 0, // IsPassed
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // PhotoUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Remark
            cursor.getInt(offset + 7), // TypeID
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // TypeName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // VideoPath
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // MapX
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // MapY
            cursor.getShort(offset + 12) != 0, // IsPhoto
            cursor.getInt(offset + 13), // UserId
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // Local
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // UserName
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // CreateTime
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17) // TemplateAttributeJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, InspectItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setInspectId(cursor.getInt(offset + 1));
        entity.setStepId(cursor.getInt(offset + 2));
        entity.setStepName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsPassed(cursor.getShort(offset + 4) != 0);
        entity.setPhotoUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRemark(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTypeID(cursor.getInt(offset + 7));
        entity.setTypeName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setVideoPath(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMapX(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setMapY(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setIsPhoto(cursor.getShort(offset + 12) != 0);
        entity.setUserId(cursor.getInt(offset + 13));
        entity.setLocal(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setUserName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCreateTime(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTemplateAttributeJson(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(InspectItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(InspectItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(InspectItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
