package com.sinodom.elevator.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sinodom.elevator.db.Location;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOCATION".
*/
public class LocationDao extends AbstractDao<Location, Long> {

    public static final String TABLENAME = "LOCATION";

    /**
     * Properties of entity Location.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, int.class, "UserId", false, "USER_ID");
        public final static Property Guid = new Property(2, String.class, "Guid", false, "GUID");
        public final static Property BaiduMapX = new Property(3, String.class, "BaiduMapX", false, "BAIDU_MAP_X");
        public final static Property BaiduMapY = new Property(4, String.class, "BaiduMapY", false, "BAIDU_MAP_Y");
        public final static Property UpdateDate = new Property(5, String.class, "UpdateDate", false, "UPDATE_DATE");
        public final static Property LongitudeAndLatitude = new Property(6, String.class, "LongitudeAndLatitude", false, "LONGITUDE_AND_LATITUDE");
    }


    public LocationDao(DaoConfig config) {
        super(config);
    }
    
    public LocationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOCATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: UserId
                "\"GUID\" TEXT," + // 2: Guid
                "\"BAIDU_MAP_X\" TEXT," + // 3: BaiduMapX
                "\"BAIDU_MAP_Y\" TEXT," + // 4: BaiduMapY
                "\"UPDATE_DATE\" TEXT," + // 5: UpdateDate
                "\"LONGITUDE_AND_LATITUDE\" TEXT);"); // 6: LongitudeAndLatitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOCATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Location entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String Guid = entity.getGuid();
        if (Guid != null) {
            stmt.bindString(3, Guid);
        }
 
        String BaiduMapX = entity.getBaiduMapX();
        if (BaiduMapX != null) {
            stmt.bindString(4, BaiduMapX);
        }
 
        String BaiduMapY = entity.getBaiduMapY();
        if (BaiduMapY != null) {
            stmt.bindString(5, BaiduMapY);
        }
 
        String UpdateDate = entity.getUpdateDate();
        if (UpdateDate != null) {
            stmt.bindString(6, UpdateDate);
        }
 
        String LongitudeAndLatitude = entity.getLongitudeAndLatitude();
        if (LongitudeAndLatitude != null) {
            stmt.bindString(7, LongitudeAndLatitude);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Location entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String Guid = entity.getGuid();
        if (Guid != null) {
            stmt.bindString(3, Guid);
        }
 
        String BaiduMapX = entity.getBaiduMapX();
        if (BaiduMapX != null) {
            stmt.bindString(4, BaiduMapX);
        }
 
        String BaiduMapY = entity.getBaiduMapY();
        if (BaiduMapY != null) {
            stmt.bindString(5, BaiduMapY);
        }
 
        String UpdateDate = entity.getUpdateDate();
        if (UpdateDate != null) {
            stmt.bindString(6, UpdateDate);
        }
 
        String LongitudeAndLatitude = entity.getLongitudeAndLatitude();
        if (LongitudeAndLatitude != null) {
            stmt.bindString(7, LongitudeAndLatitude);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Location readEntity(Cursor cursor, int offset) {
        Location entity = new Location( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // UserId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Guid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // BaiduMapX
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // BaiduMapY
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // UpdateDate
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // LongitudeAndLatitude
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Location entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getInt(offset + 1));
        entity.setGuid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBaiduMapX(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBaiduMapY(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUpdateDate(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLongitudeAndLatitude(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Location entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Location entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Location entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
