package com.sinodom.elevator.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sinodom.elevator.db.Parts;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PARTS".
*/
public class PartsDao extends AbstractDao<Parts, Long> {

    public static final String TABLENAME = "PARTS";

    /**
     * Properties of entity Parts.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Manufacturer = new Property(1, String.class, "Manufacturer", false, "MANUFACTURER");
        public final static Property Brand = new Property(2, String.class, "Brand", false, "BRAND");
        public final static Property Model = new Property(3, String.class, "Model", false, "MODEL");
        public final static Property InstallationTime = new Property(4, String.class, "InstallationTime", false, "INSTALLATION_TIME");
        public final static Property PartsTypeId = new Property(5, String.class, "PartsTypeId", false, "PARTS_TYPE_ID");
        public final static Property ProductName = new Property(6, String.class, "ProductName", false, "PRODUCT_NAME");
        public final static Property LiftId = new Property(7, String.class, "LiftId", false, "LIFT_ID");
        public final static Property PhotoPath = new Property(8, String.class, "photoPath", false, "PHOTO_PATH");
    }


    public PartsDao(DaoConfig config) {
        super(config);
    }
    
    public PartsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PARTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MANUFACTURER\" TEXT," + // 1: Manufacturer
                "\"BRAND\" TEXT," + // 2: Brand
                "\"MODEL\" TEXT," + // 3: Model
                "\"INSTALLATION_TIME\" TEXT," + // 4: InstallationTime
                "\"PARTS_TYPE_ID\" TEXT," + // 5: PartsTypeId
                "\"PRODUCT_NAME\" TEXT," + // 6: ProductName
                "\"LIFT_ID\" TEXT," + // 7: LiftId
                "\"PHOTO_PATH\" TEXT);"); // 8: photoPath
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PARTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Parts entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Manufacturer = entity.getManufacturer();
        if (Manufacturer != null) {
            stmt.bindString(2, Manufacturer);
        }
 
        String Brand = entity.getBrand();
        if (Brand != null) {
            stmt.bindString(3, Brand);
        }
 
        String Model = entity.getModel();
        if (Model != null) {
            stmt.bindString(4, Model);
        }
 
        String InstallationTime = entity.getInstallationTime();
        if (InstallationTime != null) {
            stmt.bindString(5, InstallationTime);
        }
 
        String PartsTypeId = entity.getPartsTypeId();
        if (PartsTypeId != null) {
            stmt.bindString(6, PartsTypeId);
        }
 
        String ProductName = entity.getProductName();
        if (ProductName != null) {
            stmt.bindString(7, ProductName);
        }
 
        String LiftId = entity.getLiftId();
        if (LiftId != null) {
            stmt.bindString(8, LiftId);
        }
 
        String photoPath = entity.getPhotoPath();
        if (photoPath != null) {
            stmt.bindString(9, photoPath);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Parts entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Manufacturer = entity.getManufacturer();
        if (Manufacturer != null) {
            stmt.bindString(2, Manufacturer);
        }
 
        String Brand = entity.getBrand();
        if (Brand != null) {
            stmt.bindString(3, Brand);
        }
 
        String Model = entity.getModel();
        if (Model != null) {
            stmt.bindString(4, Model);
        }
 
        String InstallationTime = entity.getInstallationTime();
        if (InstallationTime != null) {
            stmt.bindString(5, InstallationTime);
        }
 
        String PartsTypeId = entity.getPartsTypeId();
        if (PartsTypeId != null) {
            stmt.bindString(6, PartsTypeId);
        }
 
        String ProductName = entity.getProductName();
        if (ProductName != null) {
            stmt.bindString(7, ProductName);
        }
 
        String LiftId = entity.getLiftId();
        if (LiftId != null) {
            stmt.bindString(8, LiftId);
        }
 
        String photoPath = entity.getPhotoPath();
        if (photoPath != null) {
            stmt.bindString(9, photoPath);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Parts readEntity(Cursor cursor, int offset) {
        Parts entity = new Parts( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Manufacturer
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Brand
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Model
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // InstallationTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // PartsTypeId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ProductName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // LiftId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // photoPath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Parts entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setManufacturer(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBrand(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setModel(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setInstallationTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPartsTypeId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setProductName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLiftId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPhotoPath(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Parts entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Parts entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Parts entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
