package com.sinodom.elevator.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sinodom.elevator.db.Session;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SESSION".
*/
public class SessionDao extends AbstractDao<Session, Long> {

    public static final String TABLENAME = "SESSION";

    /**
     * Properties of entity Session.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserID = new Property(1, int.class, "UserID", false, "USER_ID");
        public final static Property RoleId = new Property(2, int.class, "RoleId", false, "ROLE_ID");
        public final static Property LoginName = new Property(3, String.class, "LoginName", false, "LOGIN_NAME");
        public final static Property UserName = new Property(4, String.class, "UserName", false, "USER_NAME");
        public final static Property DeptId = new Property(5, int.class, "DeptId", false, "DEPT_ID");
        public final static Property RoleCode = new Property(6, String.class, "RoleCode", false, "ROLE_CODE");
    }


    public SessionDao(DaoConfig config) {
        super(config);
    }
    
    public SessionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SESSION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: UserID
                "\"ROLE_ID\" INTEGER NOT NULL ," + // 2: RoleId
                "\"LOGIN_NAME\" TEXT," + // 3: LoginName
                "\"USER_NAME\" TEXT," + // 4: UserName
                "\"DEPT_ID\" INTEGER NOT NULL ," + // 5: DeptId
                "\"ROLE_CODE\" TEXT);"); // 6: RoleCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SESSION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Session entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserID());
        stmt.bindLong(3, entity.getRoleId());
 
        String LoginName = entity.getLoginName();
        if (LoginName != null) {
            stmt.bindString(4, LoginName);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(5, UserName);
        }
        stmt.bindLong(6, entity.getDeptId());
 
        String RoleCode = entity.getRoleCode();
        if (RoleCode != null) {
            stmt.bindString(7, RoleCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Session entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserID());
        stmt.bindLong(3, entity.getRoleId());
 
        String LoginName = entity.getLoginName();
        if (LoginName != null) {
            stmt.bindString(4, LoginName);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(5, UserName);
        }
        stmt.bindLong(6, entity.getDeptId());
 
        String RoleCode = entity.getRoleCode();
        if (RoleCode != null) {
            stmt.bindString(7, RoleCode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Session readEntity(Cursor cursor, int offset) {
        Session entity = new Session( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // UserID
            cursor.getInt(offset + 2), // RoleId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // LoginName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // UserName
            cursor.getInt(offset + 5), // DeptId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // RoleCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Session entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserID(cursor.getInt(offset + 1));
        entity.setRoleId(cursor.getInt(offset + 2));
        entity.setLoginName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUserName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDeptId(cursor.getInt(offset + 5));
        entity.setRoleCode(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Session entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Session entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Session entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
