package com.sinodom.elevator.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sinodom.elevator.db.StatusAction;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STATUS_ACTION".
*/
public class StatusActionDao extends AbstractDao<StatusAction, Long> {

    public static final String TABLENAME = "STATUS_ACTION";

    /**
     * Properties of entity StatusAction.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StatusId = new Property(1, int.class, "StatusId", false, "STATUS_ID");
        public final static Property StatusName = new Property(2, String.class, "StatusName", false, "STATUS_NAME");
        public final static Property ActionName = new Property(3, String.class, "ActionName", false, "ACTION_NAME");
        public final static Property ActionDesc = new Property(4, String.class, "ActionDesc", false, "ACTION_DESC");
        public final static Property UserType = new Property(5, String.class, "UserType", false, "USER_TYPE");
        public final static Property Argument = new Property(6, int.class, "Argument", false, "ARGUMENT");
        public final static Property ID = new Property(7, int.class, "ID", false, "ID");
        public final static Property CreateTime = new Property(8, String.class, "CreateTime", false, "CREATE_TIME");
    }


    public StatusActionDao(DaoConfig config) {
        super(config);
    }
    
    public StatusActionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STATUS_ACTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STATUS_ID\" INTEGER NOT NULL ," + // 1: StatusId
                "\"STATUS_NAME\" TEXT," + // 2: StatusName
                "\"ACTION_NAME\" TEXT," + // 3: ActionName
                "\"ACTION_DESC\" TEXT," + // 4: ActionDesc
                "\"USER_TYPE\" TEXT," + // 5: UserType
                "\"ARGUMENT\" INTEGER NOT NULL ," + // 6: Argument
                "\"ID\" INTEGER NOT NULL ," + // 7: ID
                "\"CREATE_TIME\" TEXT);"); // 8: CreateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STATUS_ACTION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StatusAction entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStatusId());
 
        String StatusName = entity.getStatusName();
        if (StatusName != null) {
            stmt.bindString(3, StatusName);
        }
 
        String ActionName = entity.getActionName();
        if (ActionName != null) {
            stmt.bindString(4, ActionName);
        }
 
        String ActionDesc = entity.getActionDesc();
        if (ActionDesc != null) {
            stmt.bindString(5, ActionDesc);
        }
 
        String UserType = entity.getUserType();
        if (UserType != null) {
            stmt.bindString(6, UserType);
        }
        stmt.bindLong(7, entity.getArgument());
        stmt.bindLong(8, entity.getID());
 
        String CreateTime = entity.getCreateTime();
        if (CreateTime != null) {
            stmt.bindString(9, CreateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StatusAction entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStatusId());
 
        String StatusName = entity.getStatusName();
        if (StatusName != null) {
            stmt.bindString(3, StatusName);
        }
 
        String ActionName = entity.getActionName();
        if (ActionName != null) {
            stmt.bindString(4, ActionName);
        }
 
        String ActionDesc = entity.getActionDesc();
        if (ActionDesc != null) {
            stmt.bindString(5, ActionDesc);
        }
 
        String UserType = entity.getUserType();
        if (UserType != null) {
            stmt.bindString(6, UserType);
        }
        stmt.bindLong(7, entity.getArgument());
        stmt.bindLong(8, entity.getID());
 
        String CreateTime = entity.getCreateTime();
        if (CreateTime != null) {
            stmt.bindString(9, CreateTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StatusAction readEntity(Cursor cursor, int offset) {
        StatusAction entity = new StatusAction( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // StatusId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // StatusName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ActionName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ActionDesc
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // UserType
            cursor.getInt(offset + 6), // Argument
            cursor.getInt(offset + 7), // ID
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // CreateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StatusAction entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStatusId(cursor.getInt(offset + 1));
        entity.setStatusName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setActionName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setActionDesc(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setArgument(cursor.getInt(offset + 6));
        entity.setID(cursor.getInt(offset + 7));
        entity.setCreateTime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StatusAction entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StatusAction entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StatusAction entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
